name: whisper_flutter_app
description: "A Flutter app with offline speech-to-text using Whisper"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  record: ^6.0.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  http: ^1.2.0
  just_audio: ^0.9.36
  connectivity_plus: ^5.0.2
  provider: ^6.1.1
  tflite_flutter: ^0.10.4
  shared_preferences: ^2.5.3
  ffi: ^2.1.0
  archive: ^3.4.10
  dio: ^5.4.0
  audioplayers: ^5.2.1
  file_picker: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/
    - assets/audio/ 